# run the pipeline on changes in master branch
trigger:
  - master
# build environment - OS
pool:
  vmImage: 'ubuntu-latest'
steps:
  # build environment - Node
  - task: NodeTool@0
    inputs:
      versionSpec: '11.x'
    displayName: 'install node.js'
  # NPM task
  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'
  # Git task
  - script: |
      # remove git history and settings - to avoid inheritance
      rm -rf .git
      # re-initialise git
      git init
      git config user.name "moo-deng"
      git config user.email "g4llerton@proton.me"
      git remote add origin https://moo-deng:${GIT_TOKEN}@github.com/moo-deng/genix-backup.git
      # add and commit /docs/ folder
      git add docs
      git commit -m "deploy the bundle"
      # push the commit to the public repository
      git push origin HEAD:master --force
    displayName: 'deploy the production bundle'